### ISSUE TITLE
Stickies to assign roles

### ISSUE THREAD

**Issue by shwina** [gvwilson/sticky-note-teaching#8]
One additional way I've seen/used sticky notes is in assigning roles to people, especially in pair programming. For example, in the Software Carpentry Git workshop's collaboration exercise, "Wolfman" is assigned a red sticky and "Dracula" will don a green sticky.

I will often ask one of the learners to help me with demonstrating this exercise, and using stickies on our laptops during the demonstration helps the rest of the learners keep track of who should be doing what.

**Comment by gvwilson** [comment]
Added in 141a035 - thanks!
